### ISSUE TITLE
Resolved: deferral not working

### ISSUE THREAD

**Issue by neutch** [cubandave/Jamf-Interaction-Toolkit#113]
hey Dave - I met you at JNUC and have started attempting to integrate the tool into our environment. I am running into a issue with the deferral service not working properly, I'm not sure if there's a configuration mis-step causing the issue because I am not fully understanding the documentation. every time the machine checks in, it seems to be ignoring the previous deferral time that was set.

is there supposed to be a policy with a trigger called uexpolicy? what triggers am I supposed to be setting when I create a new policy to deploy with the tool?

Right now I am set up to:
Use reoccurring check-in
Packages are set to Cache
Script is set with defer 3;0
Script trigger I am not sure if this needs to be set what it should be set to.. I don't have any policies that have a trigger named uexpolicy

**Comment by cubandave** [comment]
Did you get it working ok @neutch?

Hit me up on slack @cubandave anytime.
