### ISSUE TITLE
Setup Instructions in Readme.md Not Clear About Scripts

### ISSUE THREAD

**Issue by stevewood-tx** [cubandave/Jamf-Interaction-Toolkit#23]
The "How to upload to your jamf Pro server" section of the README.MD file is not clear that the script display names in your jamf pro server need to contain the ".sh" in the name. Withouth ".sh" in the display name, the 'UEX Jamf Pro configuration tool.sh' script fails with:

ERROR: Script 00-PleaseWaitUpdater-jss.sh not found on jamf server

**Comment by cubandave** [comment]
Hey @stevewood-tx. Yeah the demo at jnuc showed up uploading via Jamf Admim.app which also makes easy to over write but if you don't do it that way it wont be found. I'll ad this to the 4.0.1 milestone to search for the name of the script without the .sh.

Thanks for pointing it out.

**Comment by cubandave** [comment]
@stevewood-tx I've modified the script by simply removing the `.sh` from each script name and it still works. I'm sure you've already identified a workaround but i appreciate you raising the issue. I'll still be updating the wiki including a video demo.

**Comment by cubandave** [comment]
61464e09c3611902b1c9c1b4eed466227bde58d3 updated api conf tool to support if the scripts were uploaded or copied

**Comment by cubandave** [comment]
New youtube video coming soon

**Comment by cubandave** [comment]
Better Wikis Created
https://github.com/cubandave/Jamf-Interaction-Toolkit/wiki/00-Setting-up-UEX-Including-Branding-and-Customising-UEX
https://github.com/cubandave/Jamf-Interaction-Toolkit/wiki/00-Upgrading-from-Previous-Version-of-UEX

I want to do a lot more here but the old API is a little Kludgy
