### ISSUE TITLE
Wiki - "Software Updates with UEX" Missing

### ISSUE THREAD

**Issue by stevewood-tx** [cubandave/Jamf-Interaction-Toolkit#24]
The "Checks" page of the wiki refers to the section "Software Updates with UEX" when talking about the SUSPACKAGE check, however that section of the wiki is not present.

Just trying to figure out what variables are mandatory for the 00-UEX-Jamf-Interaction-no-grep.sh script to be able to do SUS updates.

**Comment by cubandave** [comment]
New section [04---Apple-Software-Updates-via-UEX](https://github.com/cubandave/Jamf-Interaction-Toolkit/wiki/04---Apple-Software-Updates-via-UEX) created in wiki.
