### ISSUE TITLE
Feature to use variable for filepath

### ISSUE THREAD

**Issue by shaynawaldman** [cubandave/Jamf-Interaction-Toolkit#25]
To make this customizable for other organizations, a variable could be used in place of "/Library/Application Support/JAMF/"

ex:

```# You can customize the UEX folder location with a different path
UEXPath=""

# if custom path not set, set to default
if [[ $UEXPath == "" ]]; then
UEXPath="/Library/Application Support/JAMF/"
fi```

then replace all /Library/Application Support/JAMF with $UEXPath

**Comment by cubandave** [comment]
Hey Shayna,

I though of though but the jamf folder is overy jamf manage device and it make specifying the path eaiser for things like plustbuddy. Plus you'd have to add that as a variable to every script. if you'd like you can write it and create a pull request. Otherwise, this will probably be added to a 5.0 milestone and go on the back burner for a while.

**Comment by shaynawaldman** [comment]
Sounds good! I only brought it up because we did that, and will need to do it again for the newest uex. I'm happy to submit a pull request since I'll need to do the work anyway

**Comment by cubandave** [comment]
Good news @shaynawaldman. I've made this much more dynamic. now you'll only need to write this UEX conifugration to the master script and it will write to a plist that the other scripts read

**Comment by cubandave** [comment]
Hey @shaynawaldman this is now fixed up for you. We still need to talk about how to make this scalable automatically like you need. Could be fun!
for the info please check out
* [00 Setting up UEX Including Branding and Customising UEX>Setting Custom Paths](https://github.com/cubandave/Jamf-Interaction-Toolkit/wiki/00-Setting-up-UEX-Including-Branding-and-Customising-UEX#setting-custom-paths)
