### ISSUE TITLE
Application is relaunched before install is finished

### ISSUE THREAD

**Issue by shaynawaldman** [cubandave/Jamf-Interaction-Toolkit#27]
Seeing this in all applications so far. If the block check is selected, the agent that runs to block it from launching during install closes it. So the application is closed, patching starts, the application relaunches, the agent for block closes it, and patching finishes.

**Comment by cubandave** [comment]
I bet I know where the problem is. I’ll check it today. If I’m right. I can patch that easily 

Thanks.

**Comment by cubandave** [comment]
906596c5189e3fb97f42934ad0fbe8af6ee85072 patched with this commit. New 4.0.1 release imminent
