### ISSUE TITLE
Smart Restart not working as expected

### ISSUE THREAD

**Issue by harinathreddys401** [cubandave/Jamf-Interaction-Toolkit#31]
In 4.0.1 we are getting multiple restart prompts even through user already approved for restart. Smart restart not working as expected

**Comment by cubandave** [comment]
unable to replicate asking for logs from @harinathreddys401

**Comment by cubandave** [comment]
This was due to other policies running an oder version of UEX without that feature. Thanks for raising the Issue report!

Closing as expected behavior.
