### ISSUE TITLE
Check if user is actually presenting, or in Skype/Team/webex Call

### ISSUE THREAD

**Issue by cubandave** [cubandave/Jamf-Interaction-Toolkit#37]
'nuff said

**Comment by cubandave** [comment]
Maybe look at what files and ports are opened with activity monitor data

**Comment by rjv22** [comment]
**To check whether a skype call is running:**

lsof -p $(ps -A | grep -m1 'Skype for Business' | awk '{print $1}') | grep "Resources/CallMonitor.storyboardc"

**To check whether a skype screenshare is running:**

lsof -p $(ps -A | grep -m1 'Skype for Business' | awk '{print $1}') | grep "Resources/ScreenSharingIndicator.storyboardc"

**Comment by cubandave** [comment]
To check if a Keynote is playing
lsof -p $(ps -A | grep -m1 'Keynote' | awk '{print $1}') | grep "/Resources/KeynotePlaying.icns"

**Comment by cubandave** [comment]
**For powerpoint get the current log**
`lsof -p $(pgrep "Microsoft PowerPoint") | grep apple-device-log | tail -n 1 | awk '{ print $9 }'`

**Check the last part of the SlideShowEventLoggingObserver logs** 
`cat $(lsof -p $(pgrep "Microsoft PowerPoint") | grep apple-device-log | tail -n 1 | awk '{ print $9 }') | grep SlideShowEventLoggingObserver | tail -n 1`

If it's empty or contains `Event": "Finish` then ther user is NOT presenting
**Therefore if it contains content and does not contain `Event": "Finish` then the user is presenting**

**Comment by cubandave** [comment]
`pmset -g assertions`

boom!

**Comment by cubandave** [comment]
Woohoo!
