### ISSUE TITLE
Check and unmount previous update disks

### ISSUE THREAD

**Issue by harinathreddys401** [cubandave/Jamf-Interaction-Toolkit#38]
Hi Cubandave,

We need to check and unmount if there is any previous update disks mounted. This issue occurs when there is pending restart for previous update.

so we need some logic in UEX to check if there is any existing update disks mounted. Before running software update again need to unmount these disks

**Comment by cubandave** [comment]
Yup this runs not sure if it's needed but please send your feedback @harinathreddys401 

Thanks
