### ISSUE TITLE
Add Zoom to presentation apps

### ISSUE THREAD

**Issue by tep74** [cubandave/Jamf-Interaction-Toolkit#44]
First off, I didn't think ANYONE else used Vidyo....we just moved off it to Zoom.

**Comment by cubandave** [comment]
Does zoom have a free trial? Or a way to test the software? Then I can test it and try to add it

**Comment by cubandave** [comment]
`/Applications/zoom.us.app/Contents/Frameworks/annoter.bundle/Contents/MacOS/annoter`
this is the command that might work
`lsof -p $(pgrep zoom) | grep annoter.bundle`
need to test if this file is in use when other people are sharing since the bundle is used for annotation

**Comment by cubandave** [comment]
No go 
`/Library/Logs/zoom.us/crashlog/*-as.log` this file gets written to once screen sharing starts
but stays after screensharing is stopped and after zoom is quit.

will test if the file is written when someone else shares

**Comment by tep74** [comment]
I only played around with it a bit, but it looks like the file name changes after the meeting ends (2624-as.log while meeting, 2624.log when meeting ends)

**Comment by cubandave** [comment]
thanks @tep74 the way i'll read the out put should account for that

**Comment by cubandave** [comment]
yupperz!
